// #include <Arduino.h>
#include "main_app.h"
// #include "Tes/Turbidity.h"
// #include "Tes/Thingsboard.h"
// #include "Tes/DF_Robot_EC.h"
// #include "Tes/Suhu.h"
// #include "Tes/ds18b.h"
// #include "Tes/Jarak.h"
// #include "tesPaddle/AC_speed.h"
// #include "tesPaddle/TurbinMain.h"
// #include "Tes/DO_Kalibrasi.h"
// #include "Tes/DO.h"
// #include "Tes/pH_dfrobot.h"
// #include "Turbidity.h"
// #include "DO.h"
// #include "client.h"

// #include "Sensors/example/DO-sensor-test.hpp"
// #include "Sensors/example/EC-sensor-test.hpp"
// #include "Sensors/example/PH-sensor-test.hpp"
// #include "Sensors/example/Turb-sensor-test.hpp"
// #include "Sensors/example/lcdtes.hpp"
// #include "Sensors/example/i2cscanner.hpp"

// #include "ThingsboardApp/example/test-thingsboardApp.hpp"

// #include "testServer.hpp"
// #include "LCDHandler.h"